services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URI=
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"